export const FETCH_CATEGORIES= 'FETCH_CATEGORIES';
export const RECIVE_CATEGORIES = 'RECIVE_CATEGORIES';
export const FETCH_CATEGORIES_ITEMS = 'FETCH_CATEGORIES_ITEMS';
export const RECIVE_CATEGORY_ITEMS= 'RECIVE_CATEGORY_ITEMS'
export const FETCH_ITEM = 'FETCH_ITEM';
export const RECIVE_ITEM = 'RECIVE_ITEM';
export const ADD_ITEM='ADD_ITEM';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const GET_WISHLIST = 'GET_WISHLIST';
export const GET_OFFERS = "GET_OFFERS";
export const RECIVE_OFFERS = "RECIVE_OFFERS";
export const SEARCH_ITEM = "SEARCH_ITEM"
export const CLEAR_CART = "CLEAR_CART"




